use_frameworks!
platform :ios, '8.0'

target 'SwiftJSONComparison' do

pod 'Alamofire', '3.1.2'
pod 'Argo', '2.2.0'
pod 'JSONJoy-Swift', '1.0.0'
pod 'ObjectMapper', '1.0.1'
pod 'SwiftyJSON', '2.3.1'
pod 'Runes', '3.1.0'

end

target 'SwiftJSONComparisonTests' do

end

