use_frameworks!
platform :ios, '8.0'

target 'SwiftJSONComparison' do

pod 'Alamofire', '1.2.3'
pod 'Argo', '1.0.3'
pod 'ObjectMapper', '0.12'
pod 'SwiftyJSON', '2.2.0'

end

target 'SwiftJSONComparisonTests' do

end

